    version: '3.7'
name: testing_python
services:
  fastapi:
    container_name: testing_python
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - SOME_ENV=true
