version: '3'
services:
    db:
      image: "saplabs/hanaexpress"
      hostname: hxehost
      restart: "unless-stopped"
      ports:
        - 39013:39013
        - 39017:39017
        - 39041-39045:39041-39045
        - 1128-1129:1128-1129
        - 59013-59014:59013-59014
        - 49013:49013
        - 49015:49015
        - 49041-49045:49041-49045
        - 1138-1139:1128-1129
        - 59023-59024:59013-59014
        - 49030-49033:49030-49033
        - 51000-51060:51000-51060
        - 53075:53075
      volumes:
        - /hana3:/hana/mounts
      environment: 
        - DUMP_FOLDER=DUMP
        - SOURCE_SCHEMA=SOURCE
        - SCHEMA_NAME=LOCALDEV
        - SCHEMA_PWD=Localdev1
      command: >
        --agree-to-sap-license
        --dont-check-system
        --dont-check-mount-points
        --master-password HXEHana1